### ISSUE TITLE
DNS records

### ISSUE THREAD

**Issue by fmalcher** [book-monkey2-build/iteration-6-guards#1]
Please create DNS records for
* `iteration-6-routing`
* `iteration-6-lazy-loading`

**Comment by JohannesHoppe** [comment]
We must integrate https://api.cloudflare.com/ !! 😎

**Comment by fmalcher** [comment]
Yes, please 😇 But now we're almost done

**Comment by JohannesHoppe** [comment]
Done! 

![image](https://cloud.githubusercontent.com/assets/640639/20151078/17c0c7ae-a6b9-11e6-91c8-6fcfe3c7bbdd.png)
